#164694215 Receive jwt token on successfull registration
mirest/ah-haven-space-sprinters pull request #12
Opened 2019-03-25 17:27 UTC by frankopkusianwar

**What does this PR do?** 
Create a  JWT token for a new registered user  

**Description of Task to be completed?**
- register new user  
- use generic views for register user endpoint

*How should this be manually tested?*
To test locally, clone the repo and install requirements. also add the required environment variables then run the server and visit the api/user endpoint to create a new user
or visit the review app on heroku and create a new user with email,username and password

*What are the relevant pivotal tracker stories?*
#164694215]

2019-03-26 09:37 UTC, Rhytah commented
Great job, I have tested out the endpoint and works as it should. Now let's see the implementation of JWT

2019-03-26 13:29 UTC, ManuelDominic commented on authors/apps/authentication/models.py
> +        return self.encoded_jwt
please try using the Token from the rest_framework.authtoken.models, which is provided for you from the rest_framework

2019-03-26 13:34 UTC, ManuelDominic commented on authors/apps/authentication/views.py
>      # Allow any user (authenticated or not) to hit this endpoint.
Please try using the proper formats for the classes with generic views

2019-03-26 13:38 UTC, ghost requested changes
- Please check out the proper format of the use of generic views in classes
- Try using the Token from rest_framework.authtoken.models in the rest_framework package

2019-03-26 18:58 UTC, ghost submitted a review, later dismissed

2019-03-27 13:23 UTC, kimbugp requested changes

2019-03-27 13:23 UTC, kimbugp commented on authors/apps/authentication/tests/test_views.py
> +        self.assertIn('generate_auth_token', response.data)
For uniformity, you should use the same key identifier for the token for both login and sign up

2019-03-27 14:34 UTC, kimbugp commented
@frankopkusianwar , could you please ensure to follow the right commit convention.
Also  add more details to the PR description of how to test this including the request body etc.

2019-03-27 14:35 UTC, kimbugp commented
@frankopkusianwar .please reference the PT board story link on the PR description

2019-03-27 16:13 UTC, kimbugp requested changes

2019-03-27 16:13 UTC, kimbugp commented on authors/apps/authentication/serializers.py
> +        fields = ['email', 'username', 'password', 'generate_auth_token', 'token']
@frankopkusianwar , you should have one key to represent the token

2019-03-28 09:26 UTC, merged